# Generated by Django 3.0.6 on 2020-08-27 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='Company',
        ),
    ]
