# Generated by Django 3.0.6 on 2020-08-27 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20200827_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='sales',
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_of_contact', models.CharField(max_length=30)),
                ('sales', models.FloatField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.Company')),
            ],
        ),
    ]
