# Generated by Django 3.0.6 on 2020-08-27 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20200827_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='country',
            new_name='company',
        ),
    ]
